name: lager-wasm
region: fra
static_sites:
- dockerfile_path: Lager/build.Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: HurricanKai/School-Lager
  name: school-lager
  output_dir: ./bin/publish
  routes:
  - path: /
  catchall_document: index.html